-- =====================================
-- 02_create_tables.sql
-- =====================================

-- Suppliers table
CREATE TABLE suppliers (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(20)
);

-- Products table
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    supplier_id NUMBER,
    unit_price NUMBER(10,2) CHECK (unit_price > 0),
    reorder_level NUMBER NOT NULL,
    CONSTRAINT fk_product_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);

-- Inventory table
CREATE TABLE inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 0 CHECK (quantity >= 0),
    last_updated DATE DEFAULT SYSDATE,
    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- Purchase orders
CREATE TABLE purchase_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    order_date DATE DEFAULT SYSDATE,
    quantity NUMBER,
    status VARCHAR2(30),
    CONSTRAINT fk_po_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- Audit log (needed later for triggers)
CREATE TABLE audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50),
    action VARCHAR2(50),
    table_name VARCHAR2(50),
    action_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    details VARCHAR2(4000)
);
