-- ===============================
-- TABLE CREATION SCRIPT
-- ===============================

CREATE TABLE suppliers (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(20)
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    unit_price NUMBER(10,2),
    reorder_level NUMBER NOT NULL,
    supplier_id NUMBER,
    CONSTRAINT fk_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id)
);

CREATE TABLE inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 0 CHECK (quantity >= 0),
    last_updated DATE DEFAULT SYSDATE,
    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);

CREATE TABLE purchase_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    order_date DATE DEFAULT SYSDATE,
    quantity NUMBER NOT NULL,
    status VARCHAR2(30),
    CONSTRAINT fk_po_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);

CREATE TABLE audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50),
    action VARCHAR2(50),
    table_name VARCHAR2(50),
    action_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    details VARCHAR2(4000)
);

CREATE TABLE holidays (
    holiday_date DATE PRIMARY KEY,
    description VARCHAR2(100)
);
