-- Suppliers
CREATE TABLE suppliers (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(20)
);

-- Products
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    supplier_id NUMBER,
    unit_price NUMBER(10,2),
    CONSTRAINT fk_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);

-- Inventory
CREATE TABLE inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    reorder_level NUMBER NOT NULL,
    CONSTRAINT fk_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- Purchase Orders
CREATE TABLE purchase_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    order_date DATE DEFAULT SYSDATE,
    quantity NUMBER,
    status VARCHAR2(30),
    CONSTRAINT fk_po_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- Audit log
CREATE TABLE audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50),
    action VARCHAR2(50),
    table_name VARCHAR2(50),
    action_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    details VARCHAR2(4000)
);
